site_name: Minecraft Logins Lookup
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings
      default_handler: python
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
